name: wizh_trips
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_swipe_button: ^2.1.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.11.0
  intl: ^0.20.2
  modal_bottom_sheet: ^3.0.0
  photo_view: ^0.15.0
  typewritertext: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg/
    - assets/icons/
    - lib/resources/
